services:
  postgres:
    image: postgres:16
    container_name: pg-javamastery
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-javamastery
    ports:
      - "6379:6379"

volumes:
  pgdata:
